source 'https://rubygems.org'

ruby '2.6.0'

# Sinatra
gem 'sinatra'
gem 'sinatra-contrib'

group :test do
  gem 'capybara'
  gem 'rspec'
  gem 'rubocop'
  gem 'simplecov', require: false
  gem 'simplecov-console', require: false
end
group :dev do
  gem 'pry-byebug'
end

